source 'https://rubygems.org'

gem 'grpc_kit'
gem 'redis'
gem 'griffin'
gem 'opentelemetry-sdk'
gem 'opentelemetry-instrumentation-redis'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-propagator-b3'
