source 'https://rubygems.org'

gem 'grpc'
gem 'redis'
gem 'opentelemetry-sdk', '~> 1.0.0.rc2'
gem 'opentelemetry-instrumentation-redis', '~> 0.20.0'
gem 'opentelemetry-instrumentation-grpc', github: 'ahayworth/opentelemetry-ruby', branch: 'ahayworth-add-grpc-instrumentation', glob: 'instrumentation/grpc/*.gemspec'
gem 'opentelemetry-exporter-otlp', '~> 0.20.1'
gem 'opentelemetry-propagator-b3', '~> 0.19.0'
