source 'https://rubygems.org'

gem 'grpc_kit'
gem 'redis'
gem 'griffin'
gem 'opentelemetry-sdk', '~> 1.0.0.rc1'
gem 'opentelemetry-instrumentation-redis', '~> 0.18.0'
gem 'opentelemetry-exporter-otlp', '~> 0.18.0'
gem 'opentelemetry-propagator-b3', '~> 0.18.0'
