apiVersion: 1
datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      derivedFields:
        - name: TraceID
          datasourceUid: tempo
          matcherRegex: '"trace_id":"(\w+)"'
          url: $${__value.raw}
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3100/
    access: proxy
    editable: false
    isDefault: false
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['service_name']
    version: 1
  - name: Prometheus
    type: prometheus
    access: proxy
    httpMethod: POST
    url: http://prometheus:9090
    editable: false
    isDefault: true
